/**
 * Wallet & Signature Mock Utilities
 * For testing authentication flows without real wallets
 */

import crypto from 'crypto';

// ============================================================================
// MOCK WALLET ADDRESSES
// ============================================================================

export const MOCK_WALLETS = {
  user1: '0x1234567890123456789012345678901234567890',
  user2: '0x0987654321098765432109876543210987654321',
  user3: '0xabcdefabcdefabcdefabcdefabcdefabcdefabcd',
  agent1: '0x1111111111111111111111111111111111111111',
  agent2: '0x2222222222222222222222222222222222222222',
  agent3: '0x3333333333333333333333333333333333333333',
  contractMultisig: '0x5a0b54d5dc17e0aadc383d2db43b0a0d3e029c4c',
  contractSwap: '0x68b3465833fb72B5A828cCCAC310db3C41aA34A5',
  zeroAddress: '0x0000000000000000000000000000000000000000',
};

// ============================================================================
// CHALLENGE MESSAGE GENERATION
// ============================================================================

export function generateChallenge(): string {
  const timestamp = Math.floor(Date.now() / 1000);
  const nonce = crypto.randomBytes(16).toString('hex');
  return `Sign this message to prove wallet ownership: ${timestamp}:${nonce}`;
}

export function generateChallengeWithTimestamp(timestamp: number): string {
  const nonce = crypto.randomBytes(16).toString('hex');
  return `Sign this message to prove wallet ownership: ${timestamp}:${nonce}`;
}

// ============================================================================
// MOCK SIGNATURE GENERATION
// ============================================================================

/**
 * Generate a mock signature for testing.
 * In production, this would be generated by wallet.signMessage()
 * For testing, we generate a realistic-looking hex string.
 */
export function generateMockSignature(message: string, walletAddress: string): string {
  // Create a deterministic signature based on message and wallet
  const hash = crypto
    .createHash('sha256')
    .update(message + walletAddress)
    .digest('hex');

  // Return as EIP-191 format signature (0x + 130 hex chars = 65 bytes)
  return '0x' + hash + 'abcdef1234567890' + hash.slice(0, 28);
}

// ============================================================================
// MOCK HMAC SIGNATURE FOR WEBHOOKS
// ============================================================================

export function generateMockHmacSignature(payload: string, secret: string): string {
  return crypto.createHmac('sha256', secret).update(payload).digest('hex');
}

export function validateMockHmacSignature(
  payload: string,
  signature: string,
  secret: string
): boolean {
  const expectedSignature = generateMockHmacSignature(payload, secret);
  return crypto.timingSafeEqual(Buffer.from(signature), Buffer.from(expectedSignature));
}

// ============================================================================
// MOCK SIGNED MESSAGE VERIFICATION
// ============================================================================

/**
 * Mock verification of signed message.
 * In production, this would use ethers.js verifyMessage()
 */
export function verifyMockSignature(
  message: string,
  signature: string,
  expectedAddress: string
): boolean {
  // For testing purposes, we'll verify that the signature was generated
  // with the expected message and address
  const expectedSignature = generateMockSignature(message, expectedAddress);
  return signature === expectedSignature;
}

// ============================================================================
// TEST CREDENTIALS
// ============================================================================

export interface MockCredentials {
  walletAddress: string;
  challenge: string;
  signature: string;
  timestamp: number;
}

export function createMockCredentials(walletAddress: string = MOCK_WALLETS.user1): MockCredentials {
  const timestamp = Math.floor(Date.now() / 1000);
  const challenge = generateChallengeWithTimestamp(timestamp);
  const signature = generateMockSignature(challenge, walletAddress);

  return {
    walletAddress,
    challenge,
    signature,
    timestamp,
  };
}

// Pre-generated test credentials for common scenarios
export const TEST_CREDENTIALS = {
  user1: createMockCredentials(MOCK_WALLETS.user1),
  user2: createMockCredentials(MOCK_WALLETS.user2),
  user3: createMockCredentials(MOCK_WALLETS.user3),
};

// ============================================================================
// INVALID SIGNATURE SCENARIOS
// ============================================================================

export function createInvalidSignature(): string {
  return '0x' + '1234567890abcdef'.repeat(16);
}

export function createExpiredChallenge(minutesOld: number = 10): { challenge: string; timestamp: number } {
  const timestamp = Math.floor(Date.now() / 1000) - minutesOld * 60;
  return {
    challenge: generateChallengeWithTimestamp(timestamp),
    timestamp,
  };
}

// ============================================================================
// SIGNATURE BATCH GENERATION
// ============================================================================

export function createMultipleMockCredentials(count: number) {
  const credentials: MockCredentials[] = [];

  for (let i = 0; i < count; i++) {
    const address = `0x${Math.random().toString(16).slice(2).padStart(40, '0')}`;
    credentials.push(createMockCredentials(address));
  }

  return credentials;
}

// ============================================================================
// MOCK TOKEN SIGNATURES (EIP-712)
// ============================================================================

export interface MockEIP712Signature {
  domain: {
    name: string;
    version: string;
    chainId: number;
    verifyingContract: string;
  };
  types: {
    [key: string]: Array<{ name: string; type: string }>;
  };
  primaryType: string;
  message: any;
  signature: string;
}

export function createMockEIP712Signature(
  contractAddress: string = MOCK_WALLETS.contractSwap
): MockEIP712Signature {
  return {
    domain: {
      name: 'Permit2',
      version: '1',
      chainId: 1,
      verifyingContract: contractAddress,
    },
    types: {
      PermitSingle: [
        { name: 'details', type: 'PermitDetails' },
        { name: 'spender', type: 'address' },
        { name: 'sigDeadline', type: 'uint256' },
      ],
      PermitDetails: [
        { name: 'token', type: 'address' },
        { name: 'amount', type: 'uint160' },
        { name: 'expiration', type: 'uint48' },
        { name: 'nonce', type: 'uint48' },
      ],
    },
    primaryType: 'PermitSingle',
    message: {
      details: {
        token: MOCK_WALLETS.contractSwap,
        amount: '1000000000000000000',
        expiration: Math.floor(Date.now() / 1000) + 3600,
        nonce: 1,
      },
      spender: MOCK_WALLETS.contractSwap,
      sigDeadline: Math.floor(Date.now() / 1000) + 3600,
    },
    signature: generateMockSignature('permit2_signature', contractAddress),
  };
}
